version: '3'
services:
  db:
    image: "postgres:latest"
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=djangochat
      - POSTGRES_USER=superpassword
      - POSTGRES_PASSWORD=superpassword
    networks:
      - django-chat

  redis:
    container_name: redis
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - django-chat

  django:
    container_name: django
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - "8000:8000"
    command: >
      sh -c "python manage.py collectstatic --no-input && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/usr/src/app
    depends_on:
      - redis
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_DB=djangochat
      - POSTGRES_USER=superpassword
      - POSTGRES_PASSWORD=superpassword
      - POSTGRES_PORT=5432
      - DJANGO_SETTINGS_MODULE=config.settings.base
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    networks:
      - django-chat

networks:
  django-chat:

volumes:
  db-data: