# Generated by Django 4.2.5 on 2023-09-26 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
